{
 "title": "System Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU 使用率监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "10.121.177.161",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value1", "id": "1", "type": "avg" }
     ],
     "query": "host_id:10.121.177.161 AND item_id:1001",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "内存使用率监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "10.121.177.161",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value1", "id": "1", "type": "avg" }
     ],
     "query": "item_id:1002 AND host_id:10.121.177.161",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "业务网口发送速率(Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "10.121.177.161",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value1", "id": "1", "type": "avg" }
     ],
     "query": "item_id:\"1003\" AND host_id:\"10.121.177.161\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "业务网口接受速率(Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "alias": "10.121.177.161",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value1", "id": "1", "type": "avg" }
     ],
     "query": "item_id:\"1004\" AND host_id:\"10.121.177.161\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "数据盘读取速率(kBps)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "10.121.177.161",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value1", "id": "1", "type": "avg" }
     ],
     "query": "item_id:\"1005\" AND host_id:\"10.121.177.161\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "数据盘写入速率(kBps)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "alias": "10.121.177.161",
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value1", "id": "1", "type": "avg" }
     ],
     "query": "item_id:\"1004\" AND host_id:\"10.121.177.161\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU显存监控(MiB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "10.121.177.161-gpu0",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value1", "id": "1", "type": "avg" }
     ],
     "query": "host_id:10.121.177.161 AND item_id:2001",
     "timeField": "@timestamp"
    },
    {
     "alias": "10.121.177.161-gpu1",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value1", "id": "1", "type": "avg" }
     ],
     "query": "host_id:10.121.177.161 AND item_id:2002",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}